### ISSUE TITLE
Compilation Problems

### ISSUE THREAD

**Issue by rhettp** [obscurelyme/CoffeeMaker#66]
Hello @obscurelyme,

My name is Rhett and I'm a student at Missouri State University. I'm currently working on a group project in which we use various testing techniques/software on an open source project. We found and chose CoffeeMaker. I'm contacting you because my team and I are having issues getting files to compile. This is because the libraries and header files included are not being found for some reason. We are not sure why this is happening. We've tried adjusting our VSCode and IntelliSense configurations to no avail. We have also started to use Docker to see if we could find a fix, but we are all new to Docker so nothing was found. If you could provide some information or a short walkthrough on how to get the project to compile from a a fresh clone of the repo we would greatly appreciate it. Thank you for your time!

Keep up the great work,
Rhett

**Comment by obscurelyme** [comment]
Hi Rhett, 

It's great to hear that you want to use CoffeeMaker for your project! Can you post the error messages (if any) that you see from your attempts to compile? 

A short intro on how I work with the repo assuming a 100% blank slate machine.

- install [vcpkg](https://vcpkg.io/en/index.html)
- git clone CoffeeMaker
- cmake configure (from the vs code cmake task) I just open the task commands and type >cmake and CMake Configure pops up as an option. image below...

- cmake build (again, from the vs code cmake task) I just open the task commands and type >cmake and CMake Build pops up as an option. image below...

<img width="741" alt="Screen Shot 2021-11-23 at 8 23 55 PM" src="https://user-images.githubusercontent.com/80992970/143174815-f97dbd67-484b-43ea-8f17-ffc8d120deac.png"> 

<img width="739" alt="Screen Shot 2021-11-23 at 8 24 10 PM" src="https://user-images.githubusercontent.com/80992970/143174850-e1912954-7db5-47e5-bae9-c9bac3273935.png">

vcpkg should take care of all the 3rd party stuff. I feel that if you are running into include/library issues, you may not have vcpkg installed? Or at least perhaps and old version of it. the master branch of CoffeeMaker was recently just compiled yesterday for Linux, Windows, and OSX using the latest version of vcpkg.

**Comment by rhettp** [comment]
Hello @obscurelyme ,

I'm sorry for such the late reply, it slipped my mind. We were finally able to compile the project after following your instructions
and installing a few other missing libraries. Thank you for your help!

-Rhett

**Comment by obscurelyme** [comment]
Awesome! 

I will mention that there have been quite a number of changes in the past month. If you were able to get everything working then that is still very good to hear. I will close this ticket for now. Feel free to reopen if anything comes up.
